---
- name: Add pi host
  hosts: homey-pi
  tasks:
    - add_host:
        name: "homey-pi.local"
        groups: pi

- name: provision
  remote_user: root
  hosts: pi
  roles:
    - hostname
    - timezone
    - user
    - utils
    - spi
    - node
    - { role: relay-rest-api, tags: ['relay-rest-api'] }
